### ISSUE TITLE
GitHub Issues API を使って Issue 作成機能を実装する

### ISSUE THREAD

**Issue by shimizu-saffle** [KosukeSaigusa/spajam-2022#18]
https://docs.github.com/ja/rest/issues

**Comment by kosukesaigusa** [comment]
自分の GitHub アカウントの Developers Settings > Personal access tokens から GitHub アクセストークンを生成する。

GitHub API のドキュメントを参考に、

```shell
curl \
  -H "Accept: application/vnd.github+json" \ 
  -H "Authorization: token <TOKEN>" \
  https://api.github.com/repos/KosukeSaigusa/spajam-2022/issues
```

みたいな curl を叩いてみると良さそう。403 が返ってきたりしたら、GitHub アクセストークンの仕様について調査する必要があるかも。

lanuch.json に追加（local, dev, prod 全部の設定に書いて良い）：

```
"args": [
  "--debug",
  "--dart-define=FLAVOR=dev",
  "--dart-define=GITHUB_TOKEN=abcdefg"
]
```

lanuch.base.json には、適当なプレースホルダとして追加

https://docs.github.com/en/rest/issues/issues#create-an-issue
